language: python
python:
  - "2.7"
env:
  - DJANGO_SETTINGS_MODULE="settings"
# command to install dependencies
install:
  - "pip install -r src/requirements.txt"
  - "pip install coveralls"
  - "cp src/local_settings-travis.py src/local_settings.py"
# command to run tests
script:
  - "coverage run --source=shcbelpa src/manage.py test shcbelpa"
after_success:
  coveralls